### DISCUSSION TITLE
Phase switch, limit the current, different current for 1 phase and 3 phase

### DISCUSSION THREAD

**Discussion by leeyuentuen** [leeyuentuen/alfen_wallbox#43] [General]
Below (not sure if it works or not), if we have 1 phase we want to set to 16A charging, on 3 phase we want to charge max to 10A

reason is we have situation that we have e.g. 6000W solar panel. Any suggestion or improvement can always given here

```
alias: Phase switch, Change Current
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.wallbox_connector_1_max_allowed_of_phases
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.wallbox_connector_1_max_allowed_of_phases
            state: 1 phase
        sequence:
          - service: alfen_wallbox.set_current_limit
            data:
              entity_id: number.wallbox_current_limit
              limit: 16
      - conditions:
          - condition: state
            entity_id: sensor.wallbox_connector_1_max_allowed_of_phases
            state: 3 phases
        sequence:
          - service: alfen_wallbox.set_current_limit
            data:
              entity_id: number.wallbox_current_limit
              limit: 10
mode: single
```

**Comment by phulstaert** [comment]
Is there any progress on switching between one and three phases by using a service?

In the past, I could do 6A-16A at 230V single phase (this is between 1.4kW and 3.6kW) or 
6A-16A at 230V three phases (this is between 4.1kW and 11kW)
Changing the amount of used phases would require a manual action in the ACE Service Installer and would also require a reboot of the Wallbox that in its turn would require me putting my RFID card against the Wallbox.

In Waiting for a solution, I upgraded to 32A (All the electrical was already compliant, only the 'licence' stuff needed to be done (and was done remotely).
Now I run in one fase between 6 A-32A (this is 1.4kW and 7.3 kW)

All this to get the most out of my solar panels.

For the people interested in my setup; I also have a home battery that I want to charge first, but not in a way where My home battery goes to 100% and then my car to 100%.
This because my home battery can charge with 6W if it wanted to; my car cannot. So when I have for example 2000W excess power; It would be better that the car would take 8A (1840W) and the battery took the rest.

I do this by using the following script.
Essentially I use the State of Charge of my home battery (with an offset) and use that as a percentage of the available energy that goed to the car.

I set my offset to 15%; so if my battery is charged 10%; 25% of all power goes to the Wallbox.
If the battery is charged up to 70%; 85% of all available energy goes to the Wallbox.
Since this goes in steps of 230W (1A), the battery always gets a small amount of energy, but gets priority over the Wallbox

```yaml
alias: Laadpaal Solar Optimalisation
description: ""
trigger:
  - platform: time_pattern
    minutes: /1
condition:
  - condition: state
    entity_id: sensor.laadpaal_main_state_socket_1
    state: Charging Power On
action:
  - service: alfen_wallbox.set_current_limit
    data:
      entity_id: number.laadpaal_current_limit
      limit: >
        {% set discharge = states('sensor.home_battery_power_discharge_total') |float %}
        {% set charge = states('sensor.home_battery_power_charge_total') |float %}  
        {% set soc = states('sensor.home_battery_soc_total') |float / 100 %}  
        {% set LPvoltage = states('sensor.laadpaal_voltage_l1n_socket_1') |float %} 
        {% set LPamp = states('sensor.laadpaal_current_l1_socket_1') |float %} 
        {% set LPWatt = (LPvoltage * LPamp) |int %}  
        {% set GridReturn = states('sensor.dsmr_reading_electricity_currently_returned') |float * 1000 %} 
        {% set GridDelivered = states('sensor.dsmr_reading_electricity_currently_delivered') |float * 1000 %} 
        {% set WattAvailable = (GridReturn - GridDelivered + charge - discharge + LPWatt) |int %} 
        {% set offset = 0.15 %}
        {% set LPPart = [soc + offset, 1] |min %} 
        {% set NewChargeCar = [0, (WattAvailable * LPPart / LPvoltage) |int] |max %}
        {% set NewChargeAlfen = [NewChargeCar + 2, 6] |max %}
        {{NewChargeAlfen}}
mode: single
```
