### DISCUSSION TITLE
Read RFID tag

### DISCUSSION THREAD

**Discussion by GPoorten** [leeyuentuen/alfen_wallbox#88] [Q&A]
Hi,
I'm setting up an Alfen Eve Pro Single in home assistant. The RFID reader has been enabled and a local white list of RFID tags has been created.
Is there a way to see the RFID tag used for starting/stopping a charging session?
Is there a way to read the whitelist?

The goal is to create a list/database with charging sessions per tag.
Thanks a lot for the help in advance.

**Comment by leeyuentuen** [comment]
there is a transaction log in alfen wallbox. could be possible to fetch the data. but atm don't know directly how to show the log data in home assistant.

**Comment by GPoorten** [comment]
Thank you for the quick reply. I've found the transaction log, but somehow it doesn't register correctly in my box. And I can't connect the Ace installer and the integration simultaneously somehow. 
I've been trying to find if there is a property in the API/integration sending the token ID or something. I couldn't find it in this integration or the python API. Do you know if there is one?

**Comment by leeyuentuen** [comment]
can you check the latest beta version to confirm it worked?
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.38

**Reply by GPoorten** [reply]
Hi, i'll check it this weekend. Thanks

**Reply by elRadix** [reply]
how can you start or stop session in home assistant?
I know the rfid is tag, which service can be used to stop/ start a session?

**Reply by leeyuentuen** [reply]
at the moment you can only see who start/stop the session, you can't start them charging on the integration

**Comment by citoki** [comment]
I've got two RFID cards / tags and want to track each tag separately via a utility meter in home assistant. I thought this could be possible via a template as the standard helper options will not fit.
Has anybody an idea how to do that in a custom template? Something like:
```js
if (sensor.wallbox_tag_socket_1 === "12345") {
  // count the kWh from sensor.wallbox_meter_reading_socket_1 into custom utility meter for tag1
} else {
  // count the kWh from sensor.wallbox_meter_reading_socket_1 into custom utility meter for tag2
}
```

**Comment by elRadix** [comment]
I would use measure it, it's a hacs component.
It will create different utility meters for you based on your needs. 

https://github.com/danieldotnl/ha-measureit

**Reply by citoki** [reply]
Thanks for the hint. I instead created a utility meter with two tariffs (tag1 and tag2) and two automations like:
```yaml
alias: Wallbox Select Charging for Tag1
mode: single
triggers:
  - entity_id:
      - sensor.wallbox_sap_tag_socket_1
    to: 123456TAG1
    trigger: state
conditions: []
actions:
  - action: select.select_option
    metadata: {}
    data:
      option: TARIFF1
    target:
      entity_id: select.wallbox
```
