### ISSUE TITLE
Service Call for switching the solar charging mode?

### ISSUE THREAD

**Issue by ddeconin-gh** [leeyuentuen/alfen_wallbox#136]
I tried writing an automation to switch between modes depending on weather I'm on high rate tarif (green) or low rate tarif (confort).
However, I found that trying to use

device_id: 43141dba6d90ac3eb19bec1b2e59e382
domain: select
entity_id: 5e6516d1deb16a1c5a09715d0e126a7c
type: select_option
option: Comfort

isn't reliable so I'dd like to call a service instead.. Couldn't find the service to use...

D.

**Comment by JanDetrez** [comment]
Same issue here, made a small work-arround for now

in configuration.yaml
```

  alfen_green_mode:
    name: alfen_green_mode
    icon: mdi:leaf
```

an automation
```
alias: Alfen - Select Solar Mode
description: ""
trigger:
  - platform: time_pattern
    seconds: /5
condition: []
action:
  - if:
      - condition: template
        value_template: >-
          {{ (states('input_boolean.alfen_green_mode') == "on") and
          (states('select.alfen_solar_charging_mode')=="Comfort") }}
    then:
      - action: select.select_option
        metadata: {}
        data:
          option: Green
        target:
          entity_id: select.alfen_solar_charging_mode
  - if:
      - condition: template
        value_template: >-
          {{ (states('input_boolean.alfen_green_mode') == "off") and
          (states('select.alfen_solar_charging_mode')=="Green") }}
    then:
      - action: select.select_option
        metadata: {}
        data:
          option: Comfort
        target:
          entity_id: select.alfen_solar_charging_mode
mode: single

```
