### ISSUE TITLE
Timeout error causing all entities becoming unavailable

### ISSUE THREAD

**Issue by grmbl99** [leeyuentuen/alfen_wallbox#207]
I have the following script + automation to control my charging window:

Script:
```
sequence:
  - action: number.set_value
    metadata: {}
    data:
      value: "16"
    target:
      entity_id: number.laadpaal_max_station_current
alias: laadpaal max station current = 16A
description: ""
```
Automation:
```
alias: Switch laadpaal on at 23:00
description: ""
triggers:
  - trigger: time
    at: "23:00:00"
conditions: []
actions:
  - action: script.laadpaal_max_station_current_16a
    metadata: {}
    data: {}
mode: single
```

This (often) causes the following error:
```
This error originated from a custom integration.

Logger: custom_components.alfen_wallbox.coordinator
Source: helpers/update_coordinator.py:386
integration: Alfen Wallbox (documentation, issues)
First occurred: 6 March 2025 at 21:55:55 (5 occurrences)
Last logged: 8 March 2025 at 23:00:27

Timeout fetching alfen_wallbox data
```

After this error, all entities in the Alfen device turn to "unavailable". 
This can only be fixed by reloading the Alfen integration.

The integration is configured with a refresh interval of 10s and a timeout of 20s.
The following categories are set for periodic updates: generic, generic2, meter1, meter4, states, temp
