### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by phulstaert** [leeyuentuen/alfen_wallbox#83]
This is a great plugin to use, but the learning curve is very steep. 
Some documentation could ease the integration pain. I am willing to help with this, but I will need help myself.

And it begins with the simple stuff like:
- You cannot add the device in Home Assistant if the "ACE Service Installer" is connected to the device at the same time. You will get an unknown error when you try this, so first close the ACE Service Installer.
- Also it asks for a usename and password. This is the username "admin" alongside the "Owner" password. 
Simple information, but together with the first point, makes a hell in trying to find out why it will not connect.

Other stuff I don't know yet are:
- Does this plugin only uses the API or also modbus? Do I need to configure modbus and active loadbalancing or not?
- Is there a "push preferred settings" button so the integration configures the modbus and balancing settings to a default or preferred state?
- Are there examples of automations on how to best manage the amps so it stays under a certain Wattage or only uses a certain wattage compared to energy send back to the grid, energy used from the grid, production of solar, no charging if home battery not > 80% for example, etc...

Aside from very long form posts and a few lists in the github wiki, there is no sign of a much needed manual.

**Comment by leeyuentuen** [comment]
good question,

there is a kind of charging limit between 1 and 3 phase describe in this discussion:
https://github.com/leeyuentuen/alfen_wallbox/discussions/43

but if you want, you can always write something in the wiki page:
https://github.com/leeyuentuen/alfen_wallbox/wiki


What I've done is put them in 3 automation (only use when I use comfort):
first: if the active power of my P1 is higher then 4000, then I will put my wallbox to 0A:

```
alias: Wall Charge to 0A
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.p1_meter_3c39e722c91c_active_power
    for:
      hours: 0
      minutes: 0
      seconds: 0
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: select.wallbox_solar_charging_mode
        state: Comfort
        for:
          hours: 0
          minutes: 0
          seconds: 0
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: number.wallbox_power_connector_max_current_socket_1
            above: 5
            below: 6.9
      - condition: numeric_state
        entity_id: sensor.p1_meter_3c39e722c91c_active_power
        above: 4000
      - condition: numeric_state
        entity_id: sensor.wallbox_active_power_total_socket_1
        above: 1
action:
  - service: alfen_wallbox.set_current_limit
    data:
      entity_id: number.wallbox_power_connector_max_current_socket_1
      limit: 0
mode: single
```

second is put them on 6A if the value is over 3000W

```
alias: Wall Charge to 6A
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.p1_meter_3c39e722c91c_active_power
    for:
      hours: 0
      minutes: 0
      seconds: 0
    from: null
    to: null
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: select.wallbox_solar_charging_mode
        state: Comfort
        for:
          hours: 0
          minutes: 0
          seconds: 0
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: number.wallbox_power_connector_max_current_socket_1
            above: 6
      - condition: numeric_state
        entity_id: sensor.p1_meter_3c39e722c91c_active_power
        above: 3300
      - condition: numeric_state
        entity_id: sensor.wallbox_active_power_total_socket_1
        above: 1
action:
  - service: alfen_wallbox.set_current_limit
    data:
      entity_id: number.wallbox_power_connector_max_current_socket_1
      limit: 6
mode: single
```

and third one is if thee value is lower then 1600W, then I set them from 6A to 16A for fully charge,

```
alias: wallcharge 6A to 16A
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.p1_meter_3c39e722c91c_active_power
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: select.wallbox_solar_charging_mode
        state: Comfort
        for:
          hours: 0
          minutes: 0
          seconds: 0
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: number.wallbox_power_connector_max_current_socket_1
            below: 17
      - condition: numeric_state
        entity_id: sensor.p1_meter_3c39e722c91c_active_power
        below: 1600
      - condition: numeric_state
        entity_id: sensor.wallbox_active_power_total_socket_1
        above: 1
action:
  - service: alfen_wallbox.set_current_limit
    data:
      entity_id: number.wallbox_power_connector_max_current_socket_1
      limit: 16
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
mode: single
```

I've put my wallbox to only charge on 1 phase, so he can max go to 3600W charging
